language: cpp
before_install:
- #
install:
- mkdir -p $TRAVIS_BUILD_DIR/bin/
- wget https://github.com/nodemcu/nodemcu-firmware/raw/master/pre_build/latest/nodemcu_latest.bin -O $TRAVIS_BUILD_DIR/bin/nodemcu_latest.bin
- git clone https://github.com/xlfe/spiffy.git spiffy
script:
- main_firmware_size=$(stat -c %s $TRAVIS_BUILD_DIR/bin/nodemcu_latest.bin)
- spiff_firmware_offset=$(expr 65536 + $main_firmware_size + 16384)
- file_name="luasense-sensor_v${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}.bin"
- cd spiffy
- mkdir build
- mkdir files
- make all
- cd $TRAVIS_BUILD_DIR
- cp -R $TRAVIS_BUILD_DIR/app/* file/
- $TRAVIS_BUILD_DIR/spiffy/build/spiffy
- mv $TRAVIS_BUILD_DIR/spiffy/build/spiff_rom.bin $TRAVIS_BUILD_DIR/bin/spiff_rom.bin
- srec_cat -output $TRAVIS_BUILD_DIR/bin/${file_name} -binary $TRAVIS_BUILD_DIR/bin/nodemcu_latest.bin -binary $TRAVIS_BUILD_DIR/bin/spiff_rom.bin -binary -offset 0x4000
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH}"
  file: "$TRAVIS_BUILD_DIR/bin/${file_name}"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: OVFK1zFj8VFVITWIGR2UlinVoTFNjlcQZeFt4xpn+B0wLz1mAWnR//F49qLkAcZt2ca8ogbQwEyDenFfkcSKOkUpvivyDatkHEt4WAhdXeg2y3zdHjX7NntscQBpTUmwjhV/0OA0qV9sNLK5r1t45oDh2NVcpfEQTJP5oYKfe6I=
